In [5]:
import numpy as np

In [7]:
arr=np.array([3,6,32,7])

In [8]:
arr

array([ 3,  6, 32,  7])

In [9]:
arr.shape

(4,)

In [10]:
myarr=np.array([[1,2,3],[4,5,6]])

In [11]:
myarr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
myarr.shape

(2, 3)

# Array Creation : Conversion from other python structures

In [13]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size()

TypeError: 'int' object is not callable

In [17]:
listarray.size

9

In [18]:
zeros =np.zeros((3,4))

In [19]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
rng=np.arange(0,10,2)

In [21]:
rng

array([0, 2, 4, 6, 8])

In [22]:
lspace=np.linspace(0,10,5)

In [23]:
lspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
emp=np.empty((3,4))

In [25]:
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
dtype(emp)

NameError: name 'dtype' is not defined

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
# reshape and ravel are used to change the shape of the array
# ravel is used to flatten the array
# reshape is used to change the shape of the array

In [34]:
arr.shape

(99,)

In [35]:
# Numpy Axis
# Axis 0 is the rows
# Axis 1 is the columns

In [36]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x.sum(axis=0)

array([12, 15, 18])

In [38]:
# sum across axis 0 is the sum of elements in each column
# sum across axis 1 is the sum of elements in each row

In [39]:
ar.T

NameError: name 'ar' is not defined

In [40]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [42]:
x.ndim

2

In [43]:
x.nbytes

36

In [44]:
one=np.array([1,2,3,4,5,6,7,8,9,10])

In [45]:
print(one.argmax())

9


In [46]:
# argmax() returns the index of the maximum value in the array
# argmin() returns the index of the minimum value in the array

In [47]:
print(one.argsort(reverse=True))

TypeError: argsort() got an unexpected keyword argument 'reverse'

In [48]:
# sort in descending order

print(one.argsort())


[0 1 2 3 4 5 6 7 8 9]


In [49]:
print(one.argreverse())

AttributeError: 'numpy.ndarray' object has no attribute 'argreverse'

In [50]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print(ar2.sqrt())

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [52]:
print(np.sqrt(ar2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [53]:
np.where(ar2>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [55]:
np.count_nonzero(self,ar2)

NameError: name 'self' is not defined

In [56]:
np.count_nonzero(ar2)

9

In [57]:
import sys

In [58]:
py_ar = [0,3,5,6,7,8,9,10]
np_ar = np.array(py_ar)

In [59]:
sys.getsizeof(1)*len(py_ar)

224

In [60]:
np_ar.itemsize*np_ar.size

32

In [61]:
# itemsize is the size of each element in the array
# size is the total number of elements in the array